admvilla/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),

    # DataTabke
    # url(r'^table/', include('table.urls')),
    url(r'^table/', include('apps.inicio.table.urls')),

    # Select2
    url(r'^select2/', include('django_select2.urls')),

    url(r'^inicio/', include('apps.inicio.urls', namespace='inicio')),
    url(r'^servicio/', include('apps.servicios.urls', namespace='servicio')),
    url(r'^reusables/', include('apps.reusables.urls', namespace='reusables')),
]

apps/inicio/table/urls.py
#!/usr/bin/env python
# coding: utf-8
from django.conf.urls import url

from ..table.views import FeedDataView


urlpatterns = [
    url(r'^ajax/(?P<token>\w{32})/$', FeedDataView.as_view(), name='feed_data'),
]

apps/inicio/urls.py
from django.conf.urls.static import url

from .views_inicio.docente import DocenteVista, DocenteAgregar, DocenteEditar, DocenteEliminar
from .views_inicio.apoderado import ApoderadoAgregar, ApoderadoActualizar
from .views_inicio.estudiante import EstudianteVista, EstudianteAgregar, EstudianteEditar, EstudianteEliminar
from .views_inicio.persona import PersonaBuscar
from .views_inicio.inicio import Inicio

urlpatterns = [
    # Inicio - Home
    url(r'^$', Inicio.as_view(), name='inicio'),

    # Persona
    url(r'persona/buscar/(?P<dni>\d+)$', PersonaBuscar.as_view(), name='persona_buscar'),

    # Estudiante
    url(r'estudiante/$', EstudianteVista.as_view(), name='estudiante_vista'),
    url(r'estudiante/agregar/$', EstudianteAgregar.as_view(), name='estudiante_agregar'),
    url(r'estudiante/editar/(?P<pk>\d+)$', EstudianteEditar.as_view(), name='estudiante_editar'),
    url(r'estudiante/eliminar/(?P<pk>\d+)$', EstudianteEliminar.as_view(), name='estudiante_eliminar'),

    # Apoderado
    url(r'estudiante/(?P<estudiante>\d+)/agregar/apoderado/$', ApoderadoAgregar.as_view(), name='apoderado_agregar'),
    url(r'estudiante/(?P<pk>\d+)/actualizar/apoderado/$', ApoderadoActualizar.as_view(), name='apoderado_editar'),

    # Docente
    url(r'docente/$', DocenteVista.as_view(), name='docente_vista'),
    url(r'docente/agregar/$', DocenteAgregar.as_view(), name='docente_agregar'),
    url(r'docente/editar/(?P<pk>\d+)$', DocenteEditar.as_view(), name='docente_editar'),
    url(r'docente/eliminar/(?P<pk>\d+)$', DocenteEliminar.as_view(), name='docente_eliminar'),
]

apps/inicio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class upperCharField(models.CharField):
    def __init__(self, *args, **kwargs):
        self.mayusculas = kwargs.pop("mayusculas", False)
        super(upperCharField, self).__init__(*args, **kwargs)

    def get_prep_value(self, value):
        value = super(upperCharField, self).get_prep_value(value)
        if self.mayusculas:
            return value.upper()
        return value


PersonaSexos = (
    ('M', 'Masculino'),
    ('F', 'Femenino')
)


class Persona(models.Model):
    dni = models.CharField(max_length=8, unique=True)
    paterno = upperCharField(max_length=45, mayusculas=True)
    materno = upperCharField(max_length=45, mayusculas=True)
    nombre = upperCharField(max_length=50, mayusculas=True)
    fechanacimiento = models.DateField()
    sexo = models.CharField(max_length=1, choices=PersonaSexos)
    foto = models.ImageField(null=True, blank=True)
    telefono = models.CharField(null=True, blank=True, max_length=8)
    celular = models.CharField(null=True, blank=True, max_length=9)
    correo = models.EmailField(null=True, blank=True, max_length=200)
    direccion = models.CharField(null=True, blank=True, max_length=200)

    def __unicode__(self):
        return self.paterno + ' ' + self.paterno + ' ; ' + self.nombre

    def get_absolute_url(self):
        return ''


class Apoderado(models.Model):
    ocupacion = models.CharField(max_length=100, null=True, blank=True)
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT)

    def __unicode__(self):
        return self.persona.nombre

    def get_absolute_url(self):
        return ''


class Estudiante(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT, related_name="persona")
    apoderado = models.ForeignKey(Apoderado, on_delete=models.PROTECT, related_name="apoderado", null=True, blank=True)
    observacion = models.CharField(max_length=200)

    # class Meta:
    #     unique_together = (('persona', 'apoderado'),)

    def __unicode__(self):
        return 'EST: ' + self.persona.paterno + ' ' + self.persona.materno + ' ; ' + self.persona.nombre

    def get_absolute_url(self):
        return ''

    class Meta:
        ordering = ['-id']

    def SexoEstudiante(self):
        return self.persona.sexo

    def NroContacto(self):
        _telefono = ''
        _celular = ''

        if self.apoderado == None:
            return ''
        if self.apoderado.persona.telefono:
            _telefono += str(self.apoderado.persona.telefono)
        if self.apoderado.persona.celular:
            _celular += str(self.apoderado.persona.celular)
        return '%s/%s' % (
            _telefono,
            _celular
        )

    def NombreApoderado(self):
        if self.apoderado == None:
            return ''
        else:
            return '%s %s; %s' % (
                self.apoderado.persona.paterno,
                self.apoderado.persona.materno,
                self.apoderado.persona.nombre
            )


class Docente(models.Model):
    profesion = models.CharField(max_length=100)
    gradoacademico = models.CharField(max_length=100)
    observacion = models.CharField(max_length=200)
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT)

    def __unicode__(self):
        return 'DOC: ' + self.persona.nombre

    def get_absolute_url(self):
        return ''


class Institucion(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    direccion = models.CharField(max_length=200)

    def __unicode__(self):
        return 'INS: ' + self.nombre

apps/inicio/table/models.py
#!/usr/bin/env python
# coding: utf-8
""" Model for test.
"""
from django.db import models


class Person(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)

apps/inicio/table/forms.py
#!/usr/bin/env python
# coding: utf-8
from django import forms


class QueryDataForm(forms.Form):
    """
    Non-interactive form that used to organize query parameters
    of DataTables.
    """
    sEcho = forms.CharField()
    iDisplayStart = forms.IntegerField()
    iDisplayLength = forms.IntegerField()
    iColumns = forms.IntegerField()
    sSearch = forms.CharField(required=False)
    bRegex = forms.BooleanField(required=False)
    iSortingCols = forms.IntegerField(required=False)

    def __init__(self, data=None, *args, **kwargs):
        super(QueryDataForm, self).__init__(data, *args, **kwargs)
        for key in data.keys():
            if key.startswith("iSortCol"):
                self.fields[key] = forms.IntegerField()
            if key.startswith("sSortDir"):
                self.fields[key] = forms.CharField()

apps/inicio/table/views.py
#!/usr/bin/env python
# coding: utf-8
import json
from functools import reduce

from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.http import HttpResponse
from django.views.generic.list import BaseListView

from ..table.forms import QueryDataForm
from ..table.tables import TableDataMap


class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return HttpResponse(
            self.convert_context_to_json(context),
            content_type='application/json',
            **response_kwargs
        )

    def convert_context_to_json(self, context):
        """
        Convert the context dictionary into a JSON object.
        """
        return json.dumps(context, cls=DjangoJSONEncoder)


class FeedDataView(JSONResponseMixin, BaseListView):
    """
    The view to feed ajax data of table.
    """

    context_object_name = 'object_list'

    def get(self, request, *args, **kwargs):
        if not hasattr(self, 'token'):
            self.token = kwargs["token"]
        self.columns = TableDataMap.get_columns(self.token)

        query_form = QueryDataForm(request.GET)
        if query_form.is_valid():
            self.query_data = query_form.cleaned_data
        else:
            return self.render_to_response({"error": "Query form is invalid."})
        return BaseListView.get(self, request, *args, **kwargs)

    def get_queryset(self):
        model = TableDataMap.get_model(self.token)
        if model is None:
            return None
        return model.objects.all()

    def filter_queryset(self, queryset):
        def get_filter_arguments(filter_target):
            """
            Get `Q` object passed to `filter` function.
            """
            queries = []
            fields = [col.field for col in self.columns if col.searchable]
            for field in fields:
                key = "__".join(field.split(".") + ["icontains"])
                value = filter_target
                queries.append(Q(**{key: value}))
            return reduce(lambda x, y: x | y, queries)

        filter_text = self.query_data["sSearch"]
        if filter_text:
            for target in filter_text.split():
                queryset = queryset.filter(get_filter_arguments(target))
        return queryset

    def sort_queryset(self, queryset):
        def get_sort_arguments():
            """
            Get list of arguments passed to `order_by()` function.
            """
            arguments = []
            for key, value in self.query_data.items():
                if not key.startswith("iSortCol_"):
                    continue
                field = self.columns[value].field.replace('.', '__')
                dir = self.query_data["sSortDir_" + key.split("_")[1]]
                if dir == "asc":
                    arguments.append(field)
                else:
                    arguments.append("-" + field)
            return arguments
        order_args = get_sort_arguments()
        if order_args:
            queryset = queryset.order_by(*order_args)
        return queryset

    def paging_queryset(self, queryset):
        start = self.query_data["iDisplayStart"]
        length = self.query_data["iDisplayLength"]
        if length < 0:
            return queryset
        else:
            return queryset[start: start + length]

    def convert_queryset_to_values_list(self, queryset):
        # FIXME: unit test
        return [
            [col.render(obj) for col in self.columns]
            for obj in queryset
        ]

    def get_queryset_length(self, queryset):
        return queryset.count()

    def get_context_data(self, **kwargs):
        """
        Get context data for datatable server-side response.
        See http://www.datatables.net/usage/server-side
        """
        sEcho = self.query_data["sEcho"]

        context = super(BaseListView, self).get_context_data(**kwargs)
        queryset = context["object_list"]
        if queryset is not None:
            total_length = self.get_queryset_length(queryset)
            queryset = self.filter_queryset(queryset)
            display_length = self.get_queryset_length(queryset)

            queryset = self.sort_queryset(queryset)
            queryset = self.paging_queryset(queryset)
            values_list = self.convert_queryset_to_values_list(queryset)
            context = {
                "sEcho": sEcho,
                "iTotalRecords": total_length,
                "iTotalDisplayRecords": display_length,
                "aaData": values_list,
            }
        else:
            context = {
                "sEcho": sEcho,
                "iTotalRecords": 0,
                "iTotalDisplayRecords": 0,
                "aaData": [],
            }
        return context

    def render_to_response(self, context, **response_kwargs):
        return self.render_to_json_response(context)

apps/inicio/templates/docente/agregar.html
{% extends 'baseform.html' %}
{% load static %}

{% block form-header %}
    {% if formDocente.instance.pk == None %}Agregando{% else %}Actualizando{% endif %} Docente
{% endblock form-header %}
{% block form-post %}
    <script type="text/javascript">
        actionPost = 'refrescarTablaDocente';

        function refrescarTablaDocente() {
            $("#tablaDocente").DataTable().ajax.reload(null, false);
        }
    </script>
{% endblock form-post %}

{% block form-body %}
    {{ formDocente.personaid }}
    <div class="text-center lead">Informacion general de Docente</div>
    <div class="row">{% include 'campoform.html' with campo=formDocente.dni ancho=6 espacio=3 %}</div>

    {# Bloque para señalar que la persona no existe #}
    <div id='busquedaPersona' class="text-center"></div>

    <div class="row">
        {% include 'campoform.html' with campo=formDocente.paterno ancho=6 %}
        {% include 'campoform.html' with campo=formDocente.materno ancho=6 %}
    </div>
    <div class="row">
        {% include 'campoform.html' with campo=formDocente.nombre ancho=6 %}
        {% include 'campoform.html' with campo=formDocente.sexo ancho=6 %}
    </div>
    <div class="row">
        {% include 'campoform.html' with campo=formDocente.fechanacimiento ancho=6 %}
        {% include 'campoform.html' with campo=formDocente.telefono ancho=6 %}
    </div>
    <div class="row">
        {% include 'campoform.html' with campo=formDocente.celular ancho=6 %}
        {% include 'campoform.html' with campo=formDocente.correo ancho=6 %}
    </div>
    <div class="row">
        {% include 'campoform.html' with campo=formDocente.direccion ancho=6 %}
        {% include 'campoform.html' with campo=formDocente.profesion ancho=6 %}
    </div>
    <div class="row">
        {% include 'campoform.html' with campo=formDocente.gradoacademico ancho=6 %}
        {% include 'campoform.html' with campo=formDocente.observacion ancho=6 %}
    </div>
{% endblock form-body %}

{% block form-footer %}
    {% include 'button.html' with tipo="submit" clase="success" icono="save" texto="Guardar" %}
    {% include 'button.html' with tipo="submit" clase="default" icono="arrow-left" dismiss="modal" texto="Cancelar" %}
{% endblock form-footer %}

{% block form-script-end %}
    <form method="post" id="formDni">{% csrf_token %}</form>
    <div id="capaDni"></div>

    <script type="text/javascript">
        // Funcion para buscar y verificar si el dni ingresado es correcto, sino mostrar alerta
        function buscarPersona(dni, form) {
            dnivalor = dni.val();
            if (dnivalor.length < dni.attr('minlength')) {
                swal({
                    title: 'Alerta',
                    text: 'El dni ingresado es incorrecto',
                    type: 'warning'
                }).then(function (value) {
                        setTimeout(function () {
                            dni.focus();
                        }, 500);
                    }
                )
            } else {
                url = '{% url 'inicio:persona_buscar' 0 %}';
                url = url.replace('/0', '/' + dnivalor);
                form.prop('action', url).submit();
            }
        };

        // Llamar a la funcion de busqueda de persona al click del 'INPUT SEARCH' - ESTUDIANTE
        $('#id_dni').parent().find('button').on('click', function () {
            buscarPersona($('#id_dni'), $('#formDni'));
        });

        $('#id_dni').keypress(function (e) {
            if (e.keyCode == 13) {
                buscarPersona($('#id_dni'), $('#formDni'));
            }
        });


        // AjaxForm para recuperar datos desde la persona al docente
        $('#formDni').ajaxForm({
            dataType: 'json',
            target: $('#capaDni'),
            success: function (e) {
                if (e.id == 0) {
                    $('#busquedaPersona').html('<code><i class="icon fa fa-warning"></i> El dni de la persona ingresada no existe...!</code>')
                    $('#id_paterno').focus();
                } else {
                    $('#busquedaPersona').html('');
                }
                $('#id_personaid').val(e.id);
                $('#id_paterno').val(e.paterno);
                $('#id_materno').val(e.materno);
                $('#id_nombre').val(e.nombre);

                // Reformatear fecha
                fecha = e.fechanacimiento.split('/');
                fecha = fecha[1] + '/' + fecha[0] + '/' + fecha[2];
                $('#id_fechanacimiento').parent().data('datetimepicker').setDate(new Date(fecha));

                $('#id_sexo').val(e.sexo);
                $('#id_telefono').val(e.telefono);
                $('#id_celular').val(e.celular);
                $('#id_correo').val(e.correo);
                $('#id_direccion').val(e.direccion);
            }
        });
    </script>
{% endblock form-script-end %}

apps/inicio/templates/docente/eliminar.html
{% extends 'baseform.html' %}
{% load static %}

{% block form-header %}Eliminando docente{% endblock form-header %}
{% block form-post %}
    <script type="text/javascript">
        actionPost = 'refrescarTablaDocente';

        function refrescarTablaDocente() {
            $("#tablaDocente").DataTable().ajax.reload(null, false);
        }
    </script>
{% endblock form-post %}

{% block form-body %}
    <div class="row">
        <div class="col-xs-12">
            <p class="text-center"><code><i class="icon fa fa-warning"></i> ¿Esta seguro de que desea eliminar este docente...?</code></p>
        </div>
    </div>
{% endblock form-body %}

{% block form-footer %}
    {% include 'button.html' with tipo="submit" clase="danger" icono="remove" texto="Eliminar" %}
    {% include 'button.html' with tipo="submit" clase="default" icono="arrow-left" dismiss="modal" texto="Cancelar" %}
{% endblock form-footer %}

apps/inicio/templates/docente/vista.html
{% extends 'base.html' %}
{% load static %}

{% load table_tags %}

{% block titulo_pagina %}Docentes registrados{% endblock titulo_pagina %}
{% block page_name %}Lista de Docentes{% endblock page_name %}
{% block page_description %}Año 2016{% endblock page_description %}

{% block breadcrumbs %}
    {# Ruta a travex de las URLS #}
    <ol class="breadcrumb">
        <li class="active">
            ruta002
        </li>
    </ol>
{% endblock breadcrumbs %}

{% block contentido_pagina %}
    <div class="box box-solid">
        <div class="box-body">
            {% render_table tablaDocente %}
        </div>
    </div>
{% endblock contentido_pagina %}